rewrite to work with swift3
thefuntasty/Sonar pull request #3
Opened 2017-03-13 22:31 UTC by mamdouhweb

Changed files for the library to work with Swift3

2017-03-14 02:35 UTC, jakubknejzlik commented on Pod/Classes/WavesLayer.swift
> -            gradient.opacity = 0.0
Is removing all animations intentional?

2017-03-14 03:53 UTC, mamdouhweb commented on Pod/Classes/WavesLayer.swift
> -            gradient.opacity = 0.0
Oh, this was taken from 2.0.1 not from master... it needs to be resolved with master

2017-03-14 03:55 UTC, mamdouhweb commented on Pod/Classes/WavesLayer.swift
> -            gradient.opacity = 0.0
Will add those back, but I will need some time to resolve the error with Swift3

2017-03-16 04:57 UTC, mamdouhweb commented
@jakubknejzlik this should be fixed now with animation

2017-03-18 10:24 UTC, kafejo requested changes
Thanks for the pull request! I will merge it and release new version but first please remove the empty spaces that are all over the code. Cheers!

2017-03-18 10:24 UTC, kafejo commented on Pod/Classes/SonarViewCenteredLayout.swift
> +
Please clean up these unnecessary empty lines.

2017-03-18 18:58 UTC, mamdouhweb commented
@kafejo that should be done now

2017-03-19 09:33 UTC, kafejo approved these changes
Perfect! Cheers.

2017-03-19 09:34 UTC, merged